name: carreonx_project
description: "CarreonX Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# 'dependencies' must be at the very edge (no spaces)
dependencies:
  flutter:
    sdk: flutter
  
  # 'http' must have exactly 2 spaces (aligned with 'flutter' above)
  http: ^1.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# 'flutter' section for assets/fonts (no spaces)
flutter:
  uses-material-design: true