from . import auth
from . import profiles
from . import recommendation
from . import progress
from . import chatbot
from . import analytics
from . import courses
from . import dashboard
from . import interview
from . import learning
from . import Mocktest
from . import projects
from . import tracker
from . import youtube